# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import record_pb2 as proto_dot_record__pb2


class RecordStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Start = channel.unary_unary(
                '/record.Record/Start',
                request_serializer=proto_dot_record__pb2.RecordRequest.SerializeToString,
                response_deserializer=proto_dot_record__pb2.RecordReply.FromString,
                )
        self.Stop = channel.unary_unary(
                '/record.Record/Stop',
                request_serializer=proto_dot_record__pb2.RecordRequest.SerializeToString,
                response_deserializer=proto_dot_record__pb2.RecordReply.FromString,
                )


class RecordServicer(object):
    """The greeting service definition.
    """

    def Start(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecordServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=proto_dot_record__pb2.RecordRequest.FromString,
                    response_serializer=proto_dot_record__pb2.RecordReply.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=proto_dot_record__pb2.RecordRequest.FromString,
                    response_serializer=proto_dot_record__pb2.RecordReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'record.Record', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Record(object):
    """The greeting service definition.
    """

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/record.Record/Start',
            proto_dot_record__pb2.RecordRequest.SerializeToString,
            proto_dot_record__pb2.RecordReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/record.Record/Stop',
            proto_dot_record__pb2.RecordRequest.SerializeToString,
            proto_dot_record__pb2.RecordReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
