# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/record.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/record.proto\x12\x06record\"\x1d\n\rRecordRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1e\n\x0bRecordReply\x12\x0f\n\x07message\x18\x01 \x01(\t2u\n\x06Record\x12\x35\n\x05Start\x12\x15.record.RecordRequest\x1a\x13.record.RecordReply\"\x00\x12\x34\n\x04Stop\x12\x15.record.RecordRequest\x1a\x13.record.RecordReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.record_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RECORDREQUEST._serialized_start=30
  _RECORDREQUEST._serialized_end=59
  _RECORDREPLY._serialized_start=61
  _RECORDREPLY._serialized_end=91
  _RECORD._serialized_start=93
  _RECORD._serialized_end=210
# @@protoc_insertion_point(module_scope)
